enum ComponentPosition {
  TOPNAV = "topnav",
  HOMEPAGE = "homepage",
}

enum State {
  FederalCapitalTerritory = "FederalCapitalTerritory",
  Abia = "Abia",
  Adamawa = "Adamawa",
  AkwaIbom = "AkwaIbom",
  Anambra = "Anambra",
  Bauchi = "Bauchi",
  Bayelsa = "Bayelsa",
  Benue = "Benue",
  Borno = "Borno",
  CrossRiver = "Cross River",
  Delta = "Delta",
  Ebonyi = "Ebonyi",
  Edo = "Edo",
  Ekiti = "Ekiti",
  Enugu = "Enugu",
  Gombe = "Gombe",
  Imo = "Imo",
  Jigawa = "Jigawa",
  Kaduna = "Kaduna",
  Kano = "Kano",
  Katsina = "Katsina",
  Kebbi = "Kebbi",
  Kogi = "Kogi",
  Kwara = "Kwara",
  Lagos = "Lagos",
  Nassarawa = "Nassarawa",
  Niger = "Niger",
  Ogun = "Ogun",
  Ondo = "Ondo",
  Osun = "Osun",
  Oyo = "Oyo",
  Plateau = "Plateau",
  Rivers = "Rivers",
  Sokoto = "Sokoto",
  Taraba = " Taraba",
  Yobe = " Yobe",
  Zamfara = "Zamfara",
  DefaultState = "DefaultState",
}

enum Industry {
    AgricultureAndFarming = "Agriculture and Farming",
    AerospaceAndDefense = "Aerospace and Defense",
    Automotive = "Automotive",
    BankingAndFinance = "Banking and Finance",
    BiotechnologyAndPharmaceuticals = "Biotechnology and Pharmaceuticals",
    Chemicals = "Chemicals",
    ConstructionAndRealEstate = "Construction and Real Estate",
    ConsumerGoodsAndRetail = "Consumer Goods and Retail",
    Education = "Education",
    Energy = "Energy (Oil, Gas, Renewable)",
    EntertainmentAndMedia = "Entertainment and Media",
    FoodAndBeverage = "Food and Beverage",
    HealthcareAndMedicalDevices = "Healthcare and Medical Devices",
    HospitalityAndTourism = "Hospitality and Tourism",
    InformationTechnology = "Information Technology (IT)",
    Insurance = "Insurance",
    Manufacturing = "Manufacturing",
    MiningAndMetals = "Mining and Metals",
    NonProfitAndSocialServices = "Non-profit and Social Services",
    ProfessionalServices = "Professional Services (Consulting, Legal, Accounting)",
    Telecommunications = "Telecommunications",
    TransportationAndLogistics = "Transportation and Logistics",
    Utilities = "Utilities (Electricity, Water, etc.)",
    ECommerceAndOnlineRetail = "E-commerce and Online Retail",
    GamingAndEsports = "Gaming and Esports",
    EnvironmentalServices = "Environmental Services",
    FitnessAndWellness = "Fitness and Wellness",
    SpaceIndustry = "Space Industry",
    ArtificialIntelligence = "Artificial Intelligence (AI) and Machine Learning",
    VirtualReality = "Virtual Reality (VR) and Augmented Reality (AR)",
    RoboticsAndAutomation = "Robotics and Automation",
    FashionAndApparel = "Fashion and Apparel",
    SocialMediaAndDigitalMarketing = "Social Media and Digital Marketing",
    ArchitectureAndDesign = "Architecture and Design",
    SportsAndRecreation = "Sports and Recreation",
    PharmaceuticalResearchAndDevelopment = "Pharmaceutical Research and Development",
    Nanotechnology = "Nanotechnology",
    InternetOfThings = "Internet of Things (IoT)",
    PrintingAndAdditiveManufacturing3D = "3D Printing and Additive Manufacturing",
    RenewableEnergy = "Renewable Energy",
    GreenTechnologyAndSustainability = "Green Technology and Sustainability",
    Cybersecurity = "Cybersecurity",
    CryptocurrencyAndBlockchain = "Cryptocurrency and Blockchain",
    SpaceTourism = "Space Tourism",
    GeneticEngineeringAndGenomics = "Genetic Engineering and Genomics",
}
export { ComponentPosition, State };
